### ISSUE TITLE
Add Email

### ISSUE THREAD

**Issue by ThomasMancinelli** [Santa-Susana-Game-Development-Club/Game-Dev-Site#19]

**Comment by JoseRivas1998** [comment]
@ThomasMancinelli Hey if you havent gotten asb, you can get it online at https://webstores.activenetwork.com/school-software/santa_susana_high_sc/index.php?l=product_detail&p=447#.VeIvjPlViko

**Comment by ThomasMancinelli** [comment]
Got it already. Thanks anyway though.

**Comment by ThomasMancinelli** [comment]
Also, if you know Anthony and Hunter's email could you add those. If not we could just wait till Monday.

**Comment by JoseRivas1998** [comment]
Yeah I'll get their emails on monday

**Comment by ThomasMancinelli** [comment]
Alright, cool.
